name: refresh-data
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '47 2 * * 1' # runs every Monday at 2:47

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Initialize python env
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Create new export
        run: |
          python lineageos_devices_timeline.py
      - name: Pull Remote Changes
        run: git pull
      - uses: stefanzweifel/git-auto-commit-action@v4
